### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NdaruAjaa** [MixedMC/Koira-AntiCheat#1]
Players who get the op are still detected using cheats

**Comment by ClydeplayzYT590** [comment]
This is because the plugin doesn't support default permissions for Operator players but will be added in the upcoming updates. You may use a plugin that sets permission for players like RankSystem or etc.

**Comment by ClydeplayzYT590** [comment]
This is due to the plugin's lack of support for Operator players' default permissions, which will be introduced in an upcoming update. You can use a plugin like RankSystem or another one that controls player permissions to resolve this for now.

**Comment by ClydeplayzYT590** [comment]
Fixed
